### ISSUE TITLE
callerId sometimes not working on outgoing calls. Maybe very short HTTP-Delay?

### ISSUE THREAD

**Issue by danielberlin** [sipgate/sipgate.io#30]
I noticed that sometimes setting the outgoing callerId as described in ```examples/php/dial_callerId_switch.php``` does not work. To be precise, in my sipgate.io log, I see the right XML response to set the callerId, but the called phone (also a Simquadrat user, in the following referred as SQ user) doesn't see the new callerId from the sipgate.io response, but the default callerId set in the web gui.

For example, I called 491579233777 from my SQ phone 4930999888 (all numbers anonymized) where I set ```callerId=4915792301100``` and I have the following in my sipgate.io log:

```xml
30.12.2014 14:06:51

Request: from=4930999888&to=491579233777&direction=out
Response:
HTTP/1.1 200 OK
Date: Tue, 30 Dec 2014 13:06:50 GMT
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Response><Dial callerId="4915792301100"><Number>491579233777</Number></Dial></Response>
```

This exact same call arriving on the other SQ phone is coming in without ```callerId``` I set – but the default SQ number instead:

```xml
30.12.2014 14:06:55

Request: from=4930999888&to=491579233777&direction=in
Response:
HTTP/1.1 200 OK
Date: Tue, 30 Dec 2014 13:06:54 GMT
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Response/>
```

That means at the point of the outgoing call, callerId is ignored. Since this happens only sometimes, maybe my sipgate.io web server responds a little bit too slowly? Is there any timeout which seems to be very short (1 or 2 seconds) after which the outgoing call is placed without waiting for the sipgate.io response any longer? Most of my tries for calling from 4930999888 (new ```callerId 4915792301100```) to 491579233777 look correctly like this on the incoming side:

```xml
29.12.2014 18:49:05

Request:
from=4915792301100&to=491579233777&direction=in
Response:
HTTP/1.1 200 OK
Date: Mon, 29 Dec 2014 17:49:04 GMT
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Response/>
```

As a side effect, I noticed that this 18:49:05 call doesn't show up on the called parties call log (not the sipgate.io log but the normal call list that appears in the dashboard on the left). Only in the sipgate.io log instead.

**Comment by danielberlin** [comment]
Does nobody see the same behavior?

**Comment by danielberlin** [comment]
Added http://php.net/manual/de/function.flush.php directly after `echo $dom->saveXML();`. Depending on web server config, an `additional ob_flush_end()` could be required.

No, my XML response is appearing instantly, but the TCP connection to the sipgate.io URL is closed after some more seconds due to additional activity in the script that takes that long. I suggest changing the sipgate.io behavior in that way that after `<Response/>` is received, the call processing is started and no further waiting until my web server closes the TCP connection occurs.

To make it clear: From my observation, when I place an outgoing call through Simquadrat, currently the sipgate.io server sends the PUSH request to my web server, instantly gets the answer `<Response>...<Response/>`, but waits another few seconds until the call processing starts. However, it should not wait any longer after the final `<Response/>` and start the call processing immediately.

**Comment by tpxtron** [comment]
Ah, that explains it. :-)

When flushing the output buffer (either by using flush() or ob_flush_end()), that output is visible for sipgate.io.
To say it otherwise: we cannot change the behavior as we cannot read your script's/webserver's mind. We need to receive the output buffer, it doesn't matter how that is accomplished.

Besides, sipgate.io should behave as the http standard describes: The connection needs to be closed for its content to be processed.

Therefore, we strongly recommend to make sure the output of your scripts is flushed and the connection is closed as fast as possible. That should also be in your interest, as you don't want your calls to take longer than necessary to be connected.

If you have some API calls or a slow database call in the background, you should either move that to an asynchronous execution path or make sure that the depending services are as performant as possible.

**Comment by danielberlin** [comment]
OK, well HTTP standard should be followed. So let's keep this in mind when it comes to documentation and example scripts. :-)
