### ISSUE TITLE
SSL error: DH keypair

### ISSUE THREAD

**Issue by kamph** [sipgate/sipgate.io#72]
Since some weeks I always get an 600 - General IO Error for all my requests.
Details:
java.lang.RuntimeException: Could not generate DH keypair

The requested url is at the shared hosting provider uberspace.de
What could cause this from one moment to another?

**Comment by danielberlin** [comment]
Do you use a self-signed certificate?

There's a bug in Java:

http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception

**Comment by findingmarbles** [comment]
Hi @kamph kamph!

Do you still get the error?
If so, we need more information. Could you get in touch with us at support@sipgate.io?

Thanks in advance, Corinna

PS: Thank you @danielberlin for the bug-hint :)

**Comment by kamph** [comment]
Hi @findingmarbles,

it's not a self-signed certificate but the hosting provider is using Server Name Indication (SNI).
I have provided more information including a test-url in my email to support@sipgate.io on 12.11.2015. Unfortunately that email was not answered yet. :(

You you please assist? This is still an open issue.
Thank you!

**Comment by findingmarbles** [comment]
My apologies, @kamph, I was a bit trigger-happy yesterday. We're aware this is still open and are working on it. (In fact, I closed it because I knew we had done some work on it, and presumed it fixed. Then yesterday's tests revealed that those changes didn't fix it.) 
Sorry!

**Comment by JHGitty** [comment]
@findingmarbles Here are some ideas.
1. Sipgate.IO should use SSL/TLS if a "https" url is set.
2. All HTTPS url should be allowed if the certificate is valid. Otherwise it should be trigger an error ("certificate is invalid" for example).
3. Self-signed certificates should not be allowed because you may get a free certificate from the Lets Encrypt project. The second reason to not allow a self-signed certificate is that anybody could change a valid (not self-signed) certificate to it's own self-signed certificate (MITM attack).
4. To allow self-signed certificates and add more safety you should be able to set the public key of the certificate or the fingerprint or something like that in the options. Then the system would trigger an error if the certificate was changed (MITM attack).

**Comment by danielberlin** [comment]
@JHGitty I don't think any of your proposed changes are necessary. Do you use team, basic or simquadrat?

I use a Startcom SSL certificate (which you also can get without charge) also with SNI on Apache 2.4 without any problems in sipgate.io.

Regarding your point 4: The current setup in basic and simquadrat dashboards already provides a checkbox for "allow self-signed certificates" where you even can store your pubkey. Since this checkbox is not activated per default, the security concerns (MITM) you describe are negligible.

So I would just introduce the checkbox in team.

**Comment by kamph** [comment]
The hosting provider I'm experiencing the trouble with is: https://uberspace.de/
they also have free testing accounts - in case someone wants dig further into it.

**Comment by fnordian** [comment]
Currently, we are supporting SNI and Certs up to 2048 bit keysize. Bigger keys are not supported by our java (e.g. default letsencrypt, uberspace). I am looking into this right at this moment (actually for quite a while) and it's complicated.

**Comment by JHGitty** [comment]
@danielberlin I just wrote some ideas and have not checked if they are already implemented into Sipgate.IO. Sorry if they are all already integrated.

**Comment by danielberlin** [comment]
@JHGitty Interesting point. The question is, do you classify your sipgate.io traffic as "TOP SECRET" (then you would need 3072 bit according to NSA recommendations of course ;-)

I think newly generated private keys should have 3072 or more but no panic at all for existing keys which are still at least good for "SECRET"!

Have a look at this chart:

Enter "Discrete log group size: 2048" and compare the years or choose a year and compare "Discrete Logarithm/group" column:

http://www.keylength.com/en/compare/

Besides that, you should definitely make sure that your web server is correctly configured, especially regarding Strict Transport Security and TLS Fallback SCSV because these out of the box available provisions can prevent current attacks:

https://www.ssllabs.com/ssltest/

**Comment by fnordian** [comment]
@JHGitty someone should tell Oracle.

**Comment by JHGitty** [comment]
@fnordian Could you explain which exactly class in Java has this limit? I only found this on the internet: "JDK 1.5 will fix the >2048 limitation. It's due to the RSA implementation Sun was using."

But we are talking about a limit in Java 8, right?

**Comment by fnordian** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1163501

**Comment by JHGitty** [comment]
@fnordian As you can see in the last commits of the issue in your link it has been fixed in latest OpenJDK builds. Please try it again with the newest OpenJDK version 1.8.

**Comment by fnordian** [comment]
@JHGitty I've seen that they fixed in Redhat, not in the Oracle distribution. Or did I miss something?

**Comment by JHGitty** [comment]
This is the patch:
http://pkgs.fedoraproject.org/cgit/rpms/java-1.8.0-openjdk.git/tree/rh1163501.patch?h=f22

Do you think it has only be fixed for the fedora repository? Isn't this from the upstream?
I think you may check it again on your systems with the newest OpenJDK build. From which repository do you receive your OpenJDK, which distri do you use?

**Comment by fnordian** [comment]
It's not in the vanilla java repositories:

http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/c7d016751fa5/src/share/classes/com/sun/crypto/provider/DHKeyPairGenerator.java

**Comment by JHGitty** [comment]
@fnordian Oracle knows about this issue. It will hopefully be fixed in Java 9.
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8072452

I think you need to find another library to do the same until it has been fixed. Is issue is really annoying to Java developers. I don't understand why this is a priority for Oracle.

**Comment by TheCK** [comment]
@JHGitty Sorry for the late answer. Can you please try again? More secure certificates should work now.
